### ISSUE TITLE
how to use the plugin with telescope

### ISSUE THREAD

**Issue by acambas** [terje/simctl.nvim#2]
Hello, I love the extension and it works good, but i would really like if possible to use it in a way so that it uses telescope as a menu for showing and selecting items, I see in the pictures in readme that it's used like that but i'm not sure how to do that and i couldn't find anything in the docs

**Comment by terje** [comment]
Thanks for saying! I should improve the documentation on that point since I have a screenshot of it, so I'll fix that :) 

In the meantime, it's the telescope extension `ui-select` doing the work of presenting the nice selector: https://github.com/nvim-telescope/telescope-ui-select.nvim

simctl.nvim is just using the NeoVim built in `vim.ui.select()` function and this extension overrides the gui for that function.

**Comment by acambas** [comment]
thank you very much for the answer, and again many thanks for the plugin
